
# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and check service
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0  # Ensure full history is fetched
    - name: Setup .NET env
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore CardAllowedActionsService/CardAllowedActionsService.csproj
    - name: Build
      run: dotnet build --no-restore CardAllowedActionsService/CardAllowedActionsService.csproj
    - name: Restore test dependencies
      run: dotnet restore CardAllowedActionsTests/CardAllowedActionsTests.csproj
    - name: Test
      run: dotnet test CardAllowedActionsTests/CardAllowedActionsTests.csproj --configuration Release --verbosity normal
